namespace ECNOpenAI.Chat.Response
{
    /// <summary>
    /// A list of chat completion choices. Can be more than one if n is greater than 1.
    /// </summary>
    /// <inheritdoc path="https://platform.openai.com/docs/api-reference/chat/object"/>
    public class Choices
    {
        public enum Reason
        {
            stop,
            length,
            content_filter,
            tool_calls
        }

        /// <summary>
        /// The reason the model stopped generating tokens.
        /// </summary>
        public Reason finish_reason { get; set; }
        /// <summary>
        /// The index of the choice in the list of choices.
        /// </summary>
        public int index { get; set; }

        /// <summary>
        /// A chat completion message generated by the model.
        /// </summary>
        public Message message { get; set; }
    }
}
