namespace ECNOpenAI.Chat.Response
{
    /// <summary>
    /// A chat completion message generated by the model.
    /// </summary>
    /// <inheritdoc path="https://platform.openai.com/docs/api-reference/chat/object"/>
    public class Message
    {
        /// <summary>
        /// The contents of the message.
        /// </summary>
        public string content { get; set; }
        /// <summary>
        /// The tool calls generated by the model, such as function calls.
        /// </summary>
        public ToolCalls tool_calls { get; set; }
        /// <summary>
        /// The role of the author of this message.
        /// </summary>
        public string role { get; set; }
    }
}
