namespace ECNOpenAI.Chat.Response
{
    /// <summary>
    /// The tool calls generated by the model, such as function calls.
    /// </summary>
    /// <inheritdoc path="https://platform.openai.com/docs/api-reference/chat/object"/>
    public class ToolCalls
    {
        /// <summary>
        /// The ID of the tool call.
        /// </summary>
        public string id { get; set; }
        /// <summary>
        /// The type of the tool. Currently, only function is supported.
        /// </summary>
        public string type { get; set; }
        /// <summary>
        /// The function that the model called.
        /// </summary>
        public Function function { get; set; }
    }
}
